# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout the repo
      - name: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.4.0
          
      - name: Install dependencies
        run: yarn
        
      - name: Build
        run: CI=false yarn build

      # - name: rsync deployments
      #   uses: burnett01/rsync-deployments@5.2
      #   with:
      #     switches: -avzr --delete
      #     path: build/
      #     remote_path: /home/ammo/mews-client/
      #     remote_host: ${{ secrets.HOST }}
      #     remote_user: ${{ secrets.USERNAME }}
      #     remote_key: ${{ secrets.KEY }}

      # copy files from $GITHUB_WORKSPACE "." to remote "/home/ammo/mews-client/"
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "./build/"
          target: "/home/ammo/mews-client/"

      # run commands on remote via ssh
      # - name: Deploy using ssh
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.KEY }}
      #     # port: 22
      #     script: |
      #       cd /home/ammo/mews-client/
      #       yarn install --prod
      #       yarn build
      #     # pm2 restart selfbot
